adsTextAI/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.contrib.sitemaps.views import sitemap
from adsTextAIApp.sitemaps import BlogSitemap, CustomPageSitemap, StaticViewSitemap

sitemaps = {
    'blogs': BlogSitemap,
    'pages': CustomPageSitemap,
    'home': StaticViewSitemap,
}

from adsTextAIApp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('page/<slug:slug>/', views.custom_page, name='custom_page'),
    path('blog/', views.blog, name='blog'),
    path('blog/<slug:slug>/', views.blog_detail, name='blog_detail'),
    path('robots.txt', views.robots_txt),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
]

# Serving static files and media files in development
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

adsTextAIApp/models.py
from django.db import models
from django.utils import timezone
from django.utils.text import slugify
from django.urls import reverse


# Create your models here.

class Blog(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    text = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)  # Automatically set on create only
    updated = models.DateTimeField(auto_now=True)  # Automatically updated on every save
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')
    image = models.ImageField(upload_to='static/blog_images/')

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('blog_detail', kwargs={'slug': self.slug})


class Contact(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    content = models.TextField()

    def __str__(self):
        return f"Message from {self.name}"


class CustomPage(models.Model):
    tag = models.CharField(max_length=200)
    title = models.CharField(max_length=200)
    text = models.TextField()
    image = models.ImageField(upload_to='static/pages_images/')
    slug = models.SlugField(unique=True, max_length=200, blank=True)

    def save(self, *args, **kwargs):
        # Eğer slug alanı boş ise, başlıktan slug oluştur
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('custom_page', kwargs={'slug': self.slug})


class BusinessInquiry(models.Model):
    user_description = models.TextField()
    ad_product = models.CharField(max_length=20, choices=(
        ('meta_ads', 'Meta Ads'),
        ('twitter_ads', 'Twitter Ads'),
        ('tiktok_ads', 'Tiktok Ads'),
        ('google_ads', 'Google Ads'),
    ), default='google_ads')
    chatgpt_response = models.TextField(blank=True)

    def __str__(self):
        return f"Inquiry {self.id}"

adsTextAIApp/forms.py
from django import forms
from .models import Contact, BusinessInquiry


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ['name', 'email', 'content']


class BusinessInquiryForm(forms.ModelForm):
    class Meta:
        model = BusinessInquiry
        fields = ['user_description', 'ad_product']

adsTextAIApp/views.py
from django.shortcuts import redirect
from django.contrib import messages
from django.http import HttpResponse, JsonResponse
from .forms import ContactForm
from .models import CustomPage, Blog
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator
from .forms import BusinessInquiryForm
from openai import OpenAI
from decouple import config

def index(request):
    if request.method == 'POST':
        form = BusinessInquiryForm(request.POST)
        if form.is_valid():
            if request.headers.get('X-Requested-With') == 'XMLHttpRequest':
                print('form validation')
                inquiry = form.save(commit=False)
                # Optionally modify the interaction with the API based on ad_product
                # inquiry.user_description = ''
                # inquiry.ad_product = ''
                inquiry.save()
                # OpenAI ChatGPT ile iletişim kur
                api_key = config('API_KEY_AI')
                # new

                # Define the system prompt that includes the rules for each advertising platform
                system_prompt = config('PROMPT')
                assistant_prompt = config('PROMPT_SEC')
                assistant_warning = config('PROMPT_WARNING')
                xaccount = config('XACCOUNT')
                gaccount = config('GACCOUNT')
                taccount = config('TACCOUNT')
                faccount = config('FACCOUNT')
                system_rule = config('PROMPT_RULE')


                client = OpenAI(

                    api_key=api_key,  # this is also the default, it can be omitted
                )
                # Assuming 'request' is your HTTP request object in a Django view
                user_description = request.POST.get('user_description')
                ad_product = request.POST.get('ad_product')
                chat_completion = client.chat.completions.create(
                    model="gpt-4o",
                    max_tokens=2000,
                    messages=[{"role": "system", "content": system_prompt},
                              {"role": "assistant", "content": assistant_prompt},
                              {"role": "assistant", "content": assistant_warning},
                              {"role": "assistant", "content": xaccount},
                              {"role": "assistant", "content": gaccount},
                              {"role": "assistant", "content": taccount},
                              {"role": "assistant", "content": faccount},
                              {"role": "assistant", "content": system_rule},
                              {"role": "user", "content": user_description},
                              {'role': 'user', "content": 'only write this ad copy for :' + ad_product + 'platform'},
                             ]
                )

                print(chat_completion.choices[0].message.json())
                response_text = chat_completion.choices[0].message.dict()['content'].replace("html", "").replace("```", "")

                # response_text = 'dddd'
                response_data = {
                    'message': f'{response_text}'
                }
                return JsonResponse(response_data)
        else:
            # Output errors to see what's going wrong
            print(form.errors)  # This will print form errors to your console
            return JsonResponse({'status': 'error', 'errors': form.errors.as_json()})
    else:
        form = BusinessInquiryForm()
    return render(request, 'index.html', {'form': form})


def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Thank you! We will reach out to you as soon as possible.")
            return redirect('contact')
    else:
        form = ContactForm()
    return render(request, 'contact.html', {'form': form})


def custom_page(request, slug=None):
    content = get_object_or_404(CustomPage, slug=slug)
    return render(request, 'custom.html', {'content': content})


def blog(request):
    blog_list = Blog.objects.all().order_by('-publish')  # Assuming there's a date_posted field
    paginator = Paginator(blog_list, 10)  # Show 10 blogs per page
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'blog.html', {'page_obj': page_obj})


def blog_detail(request, slug=None):
    blogDetail = get_object_or_404(Blog, slug=slug)
    return render(request, 'blog_detail.html', {'post': blogDetail})


def robots_txt(request):
    lines = [
        "User-Agent: *",
        "Disallow: /admin/",
        "Allow: /",
        "Sitemap: https://www.adsgenai.com/sitemap.xml"
    ]
    return HttpResponse("\n".join(lines), content_type="text/plain")

templates/base.html
{% load django_bootstrap5 %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

    {% block title %}  <title>Free Ad Copy Generator - Create Effective Ads in Seconds</title>  {% endblock title %}
{% block meta_title %}  <meta name="title" content="Free Ad Copy Generator | Instantly Improve Your Ads | adsgenai.com"> {% endblock meta_title %}
    {% block meta_description %}  <meta name="description" content="Need quick, compelling ad text? Try our
     free ad copy generator to enhance your campaigns. Generate powerful ad text in seconds, without any cost."> {% endblock meta_description %}

    <meta name="author" content="Vural">
    <link rel="icon"  href="{% static 'favicon.ico' %}">
    <meta property="og:title" content="Free Ad Copy Generator - Create Effective Ads in Seconds" />
    <meta property="og:description" content="Need quick, compelling ad text? Try our
     free ad copy generator to enhance your campaigns. Generate powerful ad text in seconds, without any cost." />
    <meta property="og:image" content="{% static 'logomainreduce.png' %}" />
    <meta property="og:image:width" content="200" />
    <meta property="og:image:height" content="200" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">


    {# Load CSS and JavaScript #}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    {# Display django.contrib.messages as Bootstrap alerts #}
    {% bootstrap_messages %}
     <style>

        .drop-area {
            border: 2px dashed #214391;
            border-radius: 20px;
            width: auto;
            padding: 20px;
            text-align: center;
            margin-bottom: 20px;
            margin-top: 20px;
            position: relative;
        }
        .drop-area.hover {
            background-color: #f8f9fa;
        }
        .file-input {
            opacity: 0;
            position: absolute;
            height: 100%;
            width: 100%;
            top: 0;
            left: 0;
            cursor: pointer;
        }

        #image-preview {
            max-height: 200px;
            margin-top: 20px;
        }
        .image-info {
            padding-top: 10px;
        }


    /* Görüntü yüklendiğinde kapatma butonunu göster */
    .has-image .close-btn {
        display: block;
    }

    #image-preview-container {
  display: none; /* Hidden until an image is dropped or selected */
  border: 1px solid #ddd;
  margin-top: 20px;
  padding: 10px;
  position: relative; /* Bu önemli, close-btn'u konumlandırmak için */
}

.close-btn {
  display: block; /* İlk başta gizli olmamalı */
  position: absolute;
  top: 0;
  right: 0;
  background-color: transparent;
  border: none;
  border-radius: 50%;
  cursor: pointer;
  line-height: 30px;
  padding: 0 12px;
  font-weight: bold;
}

    .btn-primary {
        background-color: #214391;
        color: #ffffff;
    }
    .manual-resize-toggle {
    display: none; /* Checkbox'ı gizle */
}

.manual-resize-label {
    cursor: pointer;
    color: #000; /* İkon rengi */
    font-size: 24px; /* İkon boyutu */
}

.manual-resize-label .fa-lock {
    display: none; /* Başlangıçta kapalı kilit ikonunu gizle */
}

.manual-resize-label.unlocked .fa-lock-open {
    display: inline; /* Eğer toggle aktifse açık kilit ikonunu göster */
}

.manual-resize-label.unlocked .fa-lock {
    display: none; /* Eğer toggle aktifse kapalı kilit ikonunu gizle */
}

.manual-resize-label.locked .fa-lock-open {
    display: none; /* Eğer toggle pasifse açık kilit ikonunu gizle */
}

.manual-resize-label.locked .fa-lock {
    display: inline; /* Eğer toggle pasifse kapalı kilit ikonunu göster */
}
.resize-options {
  display: flex;
  justify-content: space-around;
}

.resize-option label {
  cursor: pointer;
  text-align: center;
}

.resize-option label img {
  width: 200px; /* Adjust as needed */
  height: auto;
  border: 2px solid transparent; /* For highlighting selected option */
}

.resize-option input[type="radio"]:checked + label img {
  border-color: #214391; /* Highlight color for selected option */
}

@media only screen and (min-width: 700px) {
  .blog-img { height: 700px; }
}
    </style>
    <!-- Öncelikle kilit ikonlarınızı yükleyin -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" rel="stylesheet" />
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-C48T3M7T50"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-C2M2KWZYJF');
</script>
</head>

<body>
<nav class="navbar navbar-expand-md navbar-light bg-light">
  <div class="container">
      <a class="navbar-brand" href="/">
      <img src="{% static 'logomainreduce.png' %}" alt="reduce image size" width="50" height="50">
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02"
            aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'index' %}">Ads Text AI</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'blog' %}">Blog</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'contact' %}">Contact</a>
        </li>
      </ul>
    </div>
  </div>
</nav>
{% block content %}
{% endblock content %}
<footer class="pt-4 my-md-5 pt-md-5 border-top bg-light">
    <div class="container">
        <div class="row">
          <div class="col-12 col-md">
            <img class="mb-2" src="{% static 'logomainreduce.png' %}" alt="ad compy text generator" width="50" height="50">
            <p>
            Our tool expertly crafts optimized ad copy tailored to diverse digital advertising platforms
                by adhering to specific guidelines and incorporating engaging, action-driven language,
                designed to enhance your marketing effectiveness and maximize audience engagement.
            </p>
              <p>Email : tvural@lookupprice.com</p>
              <small class="d-block mb-3 text-muted">adsgenai.com © 2024</small>

          </div>
          <div class="col-6 col-md text-center">
            <h5>Privacy</h5>
            <ul class="list-unstyled text-small">
                {% for post in privacy_pages %}
              <li class="mb-1"><a class="link-secondary text-decoration-none" href="{% url 'custom_page' slug=post.slug %}">{{ post.title }}</a></li>
                {% endfor %}
            </ul>
          </div>
          <div class="col-6 col-md text-center">
            <h5>Our Products</h5>
            <ul class="list-unstyled text-small">
                {% for post in products_pages %}
              <li class="mb-1"><a class="link-secondary text-decoration-none" href="{% url 'custom_page' slug=post.slug %}">{{ post.title }}</a></li>
                {% endfor %}
              <li class="mb-1"><a class="link-secondary text-decoration-none" href="/blog">Blog</a></li>
              <li class="mb-1"><a class="link-secondary text-decoration-none" href="https://www.lookupprice.com/" target="_blank">Lookupprice.com</a></li>
              <li class="mb-1"><a class="link-secondary text-decoration-none" href="https://www.imageupgradeai.com" target="_blank">Image Enhancer</a></li>
              <li class="mb-1"><a class="link-secondary text-decoration-none" href="https://www.image2textai.com" target="_blank">Image to Text AI</a></li>
              <li class="mb-1"><a class="link-secondary text-decoration-none" href="https://apps.apple.com/tr/app/nourish-cuisine/id6450790012" target="_blank">Nourish IOS App</a></li>
              <li class="mb-1"><a class="link-secondary text-decoration-none" href="https://play.google.com/store/apps/details?id=com.kasimtugrulvural.yemek&hl=en&gl=US" target="_blank">Nourish Android App</a></li>
            </ul>
          </div>
          <div class="col-6 col-md text-center">
            <h5>About</h5>
            <ul class="list-unstyled text-small">
                {% for post in about_pages %}
              <li class="mb-1"><a class="link-secondary text-decoration-none" href="{% url 'custom_page' slug=post.slug %}">{{ post.title }}</a></li>
                {% endfor %}
              <li class="mb-1"><a class="link-secondary text-decoration-none" href="/contact">Contact</a></li>
            </ul>
          </div>
        </div>
    </div>
</footer>
{% block javascript %}
{% endblock javascript %}
</body>
</html>

templates/blog_detail.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}


{% block title %} <title>{{ post.title }}</title> {% endblock title %}
   {% block meta_description %}  <meta name="description" content="{{ post.text|truncatechars_html:400 }}"> {% endblock meta_description %}


{% block meta_title %}  <meta name="title" content="{{ post.title }} | adsgenai.com "> {% endblock meta_title %}
{% block content %}
<div class="container mt-5">
    <div class="blog-post">
        <h1 class="h1 text-align-center text-center item-center my-5">{{ post.title }}</h1>
        {% if post.image %}
            <img src="{{ post.image.url }}" class="img-fluid mb-3" alt="{{ post.title }}">
        {% endif %}
        <p class="text-muted">
            Published on {{ post.publish|date:"M d, Y" }} | Status: {{ post.get_status_display }}
        </p>
        <div class="blog-content">
            {{ post.text|safe|linebreaks }}
        </div>
    </div>
</div>
{% endblock %}

templates/custom.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}

{% block title %}  <title>{{ content.title }}</title> {% endblock title %}
   {% block meta_description %}  <meta name="description" content="{{ content.text|truncatechars_html:350 }}"> {% endblock meta_description %}
{% block meta_title %}  <meta name="title" content="{{ content.title }} | adsgenai.com"> {% endblock meta_title %}

{% block content %}


<div class="container">
<h2 class="h2 items-center text-center justify-content-center m-5">{{ content.title }}</h2>
<p class="fs-5 m-5">
    {{ content.text|safe|linebreaksbr }}
</p>
</div>


{% endblock content %}

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}


{% block title %}  <title>Free Ad Copy Text Generator | Elevate Your Advertising Efforts</title> {% endblock title %}
{% block meta_title %}  <meta name="title" content="Boost Your Ads with Our Free Ad Copy Text Generator | adsgenai.com"> {% endblock meta_title %}
 {% block meta_description %}  <meta name="description" content="Boost your advertising with our free ad
 copy generator, designed to help you create effective and compelling advertisements quickly and easily.
 Ideal for marketers on a budget."> {% endblock meta_description %}



{% block content %}

    <style>

    ul {
  list-style-type: none; /* Listeden noktaları kaldırır */
}

ol {
  list-style-type: none; /* Listeden numaraları kaldırır */
}
#loader {
    display: none;
    position: absolute;
    top: 70%;
    left: 50%;
    width: 300px;
    height: 300px;
    background-image: url({% static 'loader.gif' %});
    background-size: cover;
    transform: translate(-50%, -50%);
  }

    </style>
    <style>.d-none {display: none!important;}</style>
    <div id="loader">
        <!--<img src="{% static 'loader.gif' %}" alt="Loading..." />-->
    </div>
<div class="container">
     <div class="my-5">
        <h1 class="text-center mb-2">Free Ad Copy Text Generator</h1>
        <p class="text-center mb-2 text-muted">Effortlessly Create Compelling Ad Copy in Seconds</p>
          <form id="inputForm" method="post">
              {% csrf_token %}
<label for="id_user_description" class="form-label">Business Type</label>
         {% bootstrap_field form.user_description show_label=False placeholder='Describe your business, including the main products or services you offer, your target market, and what sets you apart from competitors.'%}
<label for="id_ad_product" class="form-label">Advertising Platform</label>
         {% bootstrap_field form.ad_product show_label=False %}
              {% bootstrap_button "Run" button_type="submit" button_class="btn-primary"  %}
              </form>
    </div>
</div>
    <div class="container">

    <div class="mx-auto text-center mt-5 mb-5">
        <h3 class="h3 text-center" id="ad-title" style="display: none;">Your Generated Ad Copy: Ready to Boost Engagement</h3>
         <div id="response"></div>
    </div>
    </div>


        <div class="container">
    <div class="row mb-4 mt-4">
        <div class="col text-center">
            <h1 class="h2">Maximizing Impact: The Critical Role of Ad Titles in Digital Advertising</h1>
        </div>
    </div>
    <!-- Metin ve Görsel İçeren Flex Container -->
    <div class="row mb-4 mt-4">
        <div class="col-md-6  align-items-center">

        <p>An effective ad title acts as the gateway to your business, enticing users to click through and engage further with your brand. Here’s why ad titles are crucial and how they can significantly impact your advertising efforts.</p>

        <h2 class="mt-4 mb-2">The Importance of Ad Titles</h2>
        <ul>
            <li><strong>First Impressions Matter</strong>: Ad titles are often the first interaction potential customers have with your brand.</li>
            <li><strong>Clarity and Relevance</strong>: A clear and relevant title helps the audience immediately understand what your ad is about.</li>
            <li><strong>Boosts Click-Through Rates (CTR)</strong>: A well-formulated ad title can significantly boost the CTR of your campaigns.</li>
            <li><strong>SEO Benefits</strong>: Utilizing keywords effectively within your ad titles can improve the visibility of your ads on search engines.</li>
        </ul>

        <h2 class="mt-4 mb-2">Crafting Effective Ad Titles</h2>
        <ul>
            <li><strong>Keep It Short and Sweet</strong>: Adherence to character limits is crucial for clarity and impact.</li>
            <li><strong>Use Strong Call-to-Action (CTA)</strong>: Incorporate action-oriented language like "Buy Now" or "Learn More".</li>
            <li><strong>Highlight Unique Value Propositions</strong>: Convey what sets your product or service apart from competitors.</li>
            <li><strong>Test and Optimize</strong>: Regular testing and optimization of your ad titles are necessary to find what works best.</li>
        </ul>

        <p class="mt-4">In digital marketing, ad titles are not just a form of creative expression but a strategic tool that can determine the success of your advertising campaigns. By crafting titles that are compelling, clear, and optimized for SEO, businesses can significantly enhance the effectiveness of their digital ads.</p>


        <p>Understanding and leveraging the power of ad titles in advertising campaigns is an essential skill for marketers aiming to capture and retain the attention of their target audience in a crowded digital landscape.</p>


        </div>
        <div class="col-md-6 d-flex justify-content-center">
            <img src="{% static '1.png' %}" alt="image reducer free online" class="img-fluid">
        </div>
    </div>
    <div class="row mb-4">
        <div class="col text-center">
            <h1 class="h2">Mastering Ad Copy: Essential Tips for Effective Advertising Text</h1>
        </div>
    </div>
    <!-- Metin ve Görsel İçeren Flex Container -->
    <div class="row">
        <div class="col-md-6 d-flex justify-content-center">
            <img src="{% static '2.png' %}" alt="ad copy generator free" class="img-fluid blog-img">
        </div>
        <div class="col-md-6  align-items-center">
                 <h1 class="mb-4"></h1>
        <p>Creating effective ad text is crucial for catching the attention of your audience and compelling them to take action. Here are some essential tips to help you craft compelling advertisements.</p>

        <h2 class="mt-4 mb-3">Understand Your Audience</h2>
        <p>Know who you are writing for to tailor your message effectively, increasing relevance and engagement.</p>

        <h2 class="mt-4 mb-3">Keep It Clear and Concise</h2>
        <p>Your message should be simple and direct, conveying your message quickly and effectively within character limits.</p>

        <h2 class="mt-4 mb-3">Highlight Benefits, Not Features</h2>
        <p>Explain the benefits of your product or service to show how it can make a difference in your customers' lives.</p>

        <h2 class="mt-4 mb-3">Use Emotional Triggers</h2>
        <p>Tap into emotions like urgency, happiness, or security to motivate consumers to act immediately.</p>

        <h2 class="mt-4 mb-3">Include a Strong Call to Action</h2>
        <p>Ensure your CTA is clear and placed prominently within your ad to tell the audience exactly what to do next.</p>

        <h2 class="mt-4 mb-3">Test and Refine</h2>
        <p>Use A/B testing to compare different aspects of your ads and refine based on performance.</p>

        <h2 class="mt-4 mb-3">Use SEO Strategically</h2>
        <p>Incorporate relevant keywords to help your ad gain better visibility on search engines.</p>

        <h2 class="mt-4 mb-3">Example Ad Copy</h2>
        <ul>
            <li><strong>Headline:</strong> Unlock Endless Entertainment</li>
            <li><strong>Body:</strong> Experience crystal-clear audio with our latest wireless headphones. Enjoy music and calls all day without pausing to recharge.</li>
            <li><strong>CTA:</strong> Shop Now – Free Shipping for a Limited Time!</li>
        </ul>

        <p class="mt-4">Writing effective ad copy is a blend of art and science. By following these tips, you can create ad texts that not only capture attention but also drive conversions.</p>


            <p>Continual testing and refinement are key to mastering the art of ad copywriting, leading to better engagement and increased sales.</p>

           </div>

    </div>
</div>


{% endblock content %}

{% block javascript %}

 <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script>
    $(document).ready(function() {
        $('#inputForm').on('submit', function(e) {
            e.preventDefault();  // Formun normal submit işlemini engelle
             $('#loader').show(); // Show the loader animation
                var $btn = $(this).find('.btn-primary');
                $btn.prop('disabled', true); // Butonu devre dışı bırak
                const userInput = $('#id_user_description').val();
                // CSRF Token ayarlama
                    var adProduct = $('#id_ad_product').val(); // Assuming you have an input for this
                    var csrftoken = $('[name=csrfmiddlewaretoken]').val();
                    console.log(userInput, adProduct, csrftoken);
                $.ajaxSetup({
                    beforeSend: function(xhr, settings) {
                        if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type) && !this.crossDomain) {
                            xhr.setRequestHeader("X-CSRFToken", csrftoken);
                        }
                    }
                });
            $.ajax({
                url: '',  // Django URL'ınız
                type: 'POST',
                data:{
                        'user_description': userInput,
                        'ad_product': adProduct, // Ensure all required fields are included
                        'csrfmiddlewaretoken': csrftoken // CSRF token must be included
                    },
                success: function(response) {
                    $('#response').html(response.message);
                    $('#loader').hide();// Yanıtı sayfada göster
                    $btn.prop('disabled', false); // Butonu tekrar etkinleştir
                   $('#ad-title').css('display', 'block');
                },
                        error: function(xhr, status, error) {
                        console.error("Error: " + xhr.responseText);
                        $btn.prop('disabled', false); // Butonu tekrar etkinleştir
                        $('#loader').hide();
                    }
            });
        });
    });
    </script>

{% endblock javascript %}